name: create-yorkie-app-publish
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - packages/create-yorkie-app/**

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Setup Node 🔧
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install and Build 🔧
        run: |
          pnpm create install
          pnpm create build

      - name: Publish 🚀
        run: cd packages/create-yorkie-app && pnpm publish --provenance
        continue-on-error: true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
